### PR TITLE
commonmark: Fix build with GHC 9.0.1

### LINKED ISSUE #72: Build failure with GHC 9.0.1
```
src/Commonmark/Inlines.hs:333:10: error:
    A pragma is not allowed in this position: {-# SCC attrParser #-}
    |
333 |          {-# SCC attrParser #-} (AddAttributes <$> attrParser)
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Commonmark/Inlines.hs:337:7: error:
    A pragma is not allowed in this position: {-# SCC pDelimChunk #-}
    |
337 |   <|> {-# SCC pDelimChunk #-} pDelimChunk specmap isDelimChar
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I can't find anything about a relevant parser change in GHC's [release notes](http://downloads.haskell.org/~ghc/latest/docs/html/users_guide/9.0.1-notes.html) or the [migration guide](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0), so I'm wondering whether this could be a regression.

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes #72.

### CODE REVIEW

**Comment by jgm** [comment]
Thanks for tracking that down!
